include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    avoid_print: true
    empty_statements: true
    prefer_single_quotes: true