name: proyect_atenea
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2

  path_provider: ^2.0.11
  provider: ^6.0.5
  shared_preferences: ^2.0.15

  flutter_svg: ^2.0.10+1
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
 

  assets:
    - assets/svg/Account.svg
    - assets/svg/Account-Setting.svg
    - assets/svg/Backspace.svg
    - assets/svg/Calendar-Marked.svg
    - assets/svg/Calendar-Upcoming.svg
    - assets/svg/Historial.svg
    - assets/svg/Search-Stadistics.svg
    - assets/svg/Search.svg
    - assets/svg/Close.svg
    - assets/svg/Bearny.svg

    - assets/images/backgrounds/top_left_asset.png
    - assets/images/backgrounds/dart_vector.png
    - assets/images/backgrounds/down_left_asset.png 
    - assets/images/backgrounds/living_fime.png

  fonts:
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf