name: proyect_atenea
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
 

  assets:
    - assets/svg/Account.svg
    - assets/svg/Account-Setting.svg
    - assets/svg/Backspace.svg
    - assets/svg/Calendar-Marked.svg
    - assets/svg/Calendar-Upcoming.svg
    - assets/svg/Historial.svg
    - assets/svg/Search-Stadistics.svg
    - assets/svg/Search.svg
    - assets/svg/Close.svg


    - assets/images/backgrounds/dart_vector.png
    - assets/images/backgrounds/down_left_asset.png 
    - assets/images/backgrounds/living_fime.png

  fonts:
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf