name: proyect_atenea
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.6

  image_picker: ^0.8.7

  # Other dependencies
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  provider: ^6.0.5
  fluttertoast: ^8.2.0 
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  file_picker: ^5.5.0
  uuid: ^4.5.1
  lottie: ^3.2.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/account.svg
    - assets/svg/account_settings.svg
    - assets/svg/back_action.svg
    - assets/svg/search.svg
    - assets/svg/close.svg
    - assets/svg/Bearny.svg
    - assets/svg/book.svg
    - assets/svg/subjects.svg
    - assets/svg/user_list.svg
    - assets/svg/add.svg
    - assets/svg/edit.svg
    - assets/svg/eye.svg
    - assets/svg/trashcan.svg
    - assets/svg/replace.svg
    - assets/svg/check.svg
    - assets/svg/drag_indicator.svg
    - assets/svg/crossed_folder.svg
    - assets/svg/view_file.svg
    - assets/svg/add_user.svg
    - assets/images/backgrounds/top_left_asset.png
    - assets/images/backgrounds/dart_vector.png
    - assets/images/backgrounds/down_left_asset.png
    - assets/images/backgrounds/living_fime.png
    - assets/images/backgrounds/top_right.png
    - assets/images/backgrounds/fime.png
    - assets/images/backgrounds/uanl.png

  fonts:
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf