name: proyect_atenea
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.0.11
  provider: ^6.0.5
  fluttertoast: ^8.1.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  file_picker: ^5.0.0
  uuid: ^3.0.6
  lottie: ^3.1.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/svg/account.svg
    - assets/svg/account_settings.svg
    - assets/svg/back_action.svg
    - assets/svg/search.svg
    - assets/svg/close.svg
    - assets/svg/Bearny.svg
    - assets/svg/book.svg
    - assets/svg/subjects.svg
    - assets/svg/user_list.svg
    - assets/svg/add.svg
    - assets/svg/edit.svg
    - assets/svg/eye.svg
    - assets/svg/trashcan.svg
    
    - assets/svg/check.svg
      
    - assets/svg/drag_indicator.svg
    - assets/svg/view_file.svg
    - assets/svg/add_user.svg
    
    - assets/images/backgrounds/top_left_asset.png
    - assets/images/backgrounds/dart_vector.png
    - assets/images/backgrounds/down_left_asset.png
    - assets/images/backgrounds/living_fime.png
    - assets/images/backgrounds/top_right.png
    - assets/images/backgrounds/fime.png
    - assets/images/backgrounds/uanl.png

  fonts:
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf