name: proyect_atenea
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg 
  assets:
    - assets/svg/Account.svg
    - assets/svg/Account-Setting.svg
    - assets/svg/Backspace.svg
    - assets/svg/Calendar-Marked.svg
    - assets/svg/Calendar-Upcoming.svg
    - assets/svg/Historial.svg
    - assets/svg/Search-Stadistics.svg
    - assets/svg/Search.svg

  fonts:
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf