// File generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OGWpxPf3AxIdXuB7DLt1Vz2LLOI1KJI',
    appId: '1:707092644639:web:8e2ea1807bf21f5a79662a',
    messagingSenderId: '707092644639',
    projectId: 'athenea-fime',
    authDomain: 'athenea-fime.firebaseapp.com',
    storageBucket: 'athenea-fime.appspot.com',
    measurementId: 'G-1GMGP3T2H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBnerDHAlD235ulHUjbwZ51IfmFvOMZo',
    appId: '1:707092644639:android:4170ce6797833bce79662a',
    messagingSenderId: '707092644639',
    projectId: 'athenea-fime',
    storageBucket: 'athenea-fime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZoGo695CAJGoy1jA4eyIHgA4tQwuHMc',
    appId: '1:707092644639:ios:f14d7beec9c167fe79662a',
    messagingSenderId: '707092644639',
    projectId: 'athenea-fime',
    storageBucket: 'athenea-fime.appspot.com',
    iosBundleId: 'com.mike.proyectAtenea',
  );

}